-- Create Quality Standards Table
CREATE TABLE IF NOT EXISTS quality_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    unit TEXT,
    method TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migrate existing parameters from specs (avoid duplicates)
INSERT INTO quality_standards (name, unit, method)
SELECT DISTINCT parameter_name, unit, method
FROM quality_specs
ON CONFLICT (name) DO NOTHING;

-- Add Defaults if missing
INSERT INTO quality_standards (name, unit, method) VALUES
('Görünüş', '', 'Görsel'),
('Renk', '', 'Görsel'),
('Koku', '', 'Organoleptik'),
('pH', '', 'pH Metre'),
('Yoğunluk', 'g/cm3', 'Piknometre'),
('Viskozite', 'cP', 'Viskozimetre'),
('Kırılma İndisi', '', 'Refraktometre'),
('Aktif Madde', '%', 'Titrasyon')
ON CONFLICT (name) DO NOTHING;
