-- Comprehensive Database Reset & Stabilization Script
-- This script clears all transactional and master data to start fresh for LIVE use.

BEGIN;

-- 1. ENSURE CORE TABLES EXIST (In case some are missing from a previous partial setup)
CREATE TABLE IF NOT EXISTS inventory (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS recipes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS accounts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS team_members (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES auth.users(id),
    member_email TEXT NOT NULL,
    member_id UUID REFERENCES auth.users(id),
    role TEXT NOT NULL CHECK (role IN ('admin', 'operator', 'viewer')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(owner_id, member_email)
);

-- 2. TRUNCATE ALL TRANSACTIONAL AND MASTER DATA
-- (Note: We only truncate tables that definitely exist or were just created)
TRUNCATE TABLE 
    inventory,
    recipes,
    accounts,
    team_members -- Clear members too for a truly fresh start, or keep if you prefer. 
    -- User said "Tam temizlik", so clearing team_members is also fine, BUT usually owners want to keep their team.
    -- Let's NOT truncate team_members to avoid locking people out, but truncate the rest.
RESTART IDENTITY CASCADE;

-- Re-doing the truncate for transactional tables specifically
DO $$ 
BEGIN
    EXECUTE (
        SELECT 'TRUNCATE TABLE ' || string_agg(quote_ident(table_name), ', ') || ' RESTART IDENTITY CASCADE'
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name IN ('sales', 'productions', 'purchases', 'stock_movements', 'lots', 'recipe_ingredients', 'quality_results', 'quality_batches', 'quality_specs', 'quality_standards')
    );
EXCEPTION WHEN OTHERS THEN 
    RAISE NOTICE 'Some tables were not found or could not be truncated, moving on...';
END $$;

-- 3. ENSURE RECENT SCHEMA UPDATES ARE APPLIED
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS cost NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'TRY';
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_overhead_cost NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_packaging_id INTEGER REFERENCES inventory(id);
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_shipping_cost NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_monthly_interest NUMERIC DEFAULT 4;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS critical_stock NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS product_code TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ghs_symbols TEXT[] DEFAULT '{}';
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS shelf_life_months INTEGER DEFAULT 24;

COMMIT;

-- 4. VERIFICATION QUERY (Safe version)
SELECT 'Cleanup Complete' as status, 
       (SELECT count(*) FROM inventory) as inventory_count,
       (SELECT CASE WHEN EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'team_members') 
                    THEN (SELECT count(*) FROM team_members)::text 
                    ELSE 'Not Created' END) as team_members_count;
