-- IBC Deposit Tracking (IBC Depozito Takibi) Schema
CREATE TABLE IF NOT EXISTS ibc_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    customer_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN ('Sent', 'Returned')),
    quantity INTEGER NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_ibc_customer ON ibc_movements(customer_id);
CREATE INDEX IF NOT EXISTS idx_ibc_user ON ibc_movements(user_id);
