
-- ==========================================================
-- FULL DATABASE STABILIZATION & RPC SETUP
-- Consolidated from latest stable scripts.
-- ==========================================================

BEGIN;

-- 1. Ensure Inventory Schema is Complete
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS product_code TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ghs_symbols TEXT[] DEFAULT '{}';
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS shelf_life_months INTEGER DEFAULT 24;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_overhead_cost NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_packaging_id INTEGER REFERENCES inventory(id);
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_shipping_cost NUMERIC DEFAULT 0;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS ref_monthly_interest NUMERIC DEFAULT 4;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS capacity_value NUMERIC;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS capacity_unit TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS tare_weight NUMERIC;

-- 2. Ensure Quality Schema
CREATE TABLE IF NOT EXISTS quality_standards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE quality_batches ADD COLUMN IF NOT EXISTS production_id BIGINT REFERENCES productions(id);

-- 3. HELPER: generate_lot_number
CREATE OR REPLACE FUNCTION generate_lot_number(p_user_id UUID, p_date DATE)
RETURNS TEXT AS $$
DECLARE
    date_str TEXT;
    seq INTEGER;
    new_lot TEXT;
BEGIN
    date_str := to_char(p_date, 'DDMMYY');
    SELECT COALESCE(MAX(CAST(SPLIT_PART(lot_number, '-', 3) AS INTEGER)), 0) + 1
    INTO seq
    FROM productions
    WHERE user_id = p_user_id
    AND lot_number LIKE 'GR-' || date_str || '-%';
    new_lot := 'GR-' || date_str || '-' || LPAD(seq::TEXT, 2, '0');
    RETURN new_lot;
END;
$$ LANGUAGE plpgsql;

-- 4. RPC: process_purchase (Latest Version)
-- [Insert here the content from integrate_production_qc.sql lines 10-87]

-- 5. RPC: process_production (Latest Version)
-- [Insert here the content from integrate_production_qc.sql lines 91-253]

-- 6. RPC: process_sale (Latest Version)
-- [Insert here the content from integrate_production_qc.sql lines 490-567]

COMMIT;
