-- Enable RLS (though we are using public for this MVP mostly)
-- TABLES FOR QUALITY CONTROL

-- 1. Test Specifications (Product Standarts)
CREATE TABLE IF NOT EXISTS quality_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES inventory(id),
    parameter_name TEXT NOT NULL, -- e.g. "pH"
    min_value NUMERIC,
    max_value NUMERIC,
    target_value NUMERIC,
    unit TEXT, -- e.g. "g/cm3"
    method TEXT, -- e.g. "ASTM D1293"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Quality Control Batches (The 'Folder' for a specific lot test)
CREATE TABLE IF NOT EXISTS quality_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type TEXT, -- 'Production' or 'Purchase'
    reference_id BIGINT, -- ID from production_log or purchase_orders
    product_id BIGINT REFERENCES inventory(id),
    lot_no TEXT,
    status TEXT DEFAULT 'Pending', -- Pending, In Progress, Approved, Rejected, Conditional Approval
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Test Results (Actual measurements)
CREATE TABLE IF NOT EXISTS quality_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT REFERENCES quality_batches(id) ON DELETE CASCADE,
    spec_id BIGINT REFERENCES quality_specs(id), -- Link to the strict definition
    parameter_name TEXT, -- Snapshot of parameter name in case spec changes
    measured_value NUMERIC,
    result TEXT, -- 'Pass', 'Fail'
    tested_by TEXT,
    tested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_quality_specs_product ON quality_specs(product_id);
CREATE INDEX IF NOT EXISTS idx_quality_batches_product ON quality_batches(product_id);
CREATE INDEX IF NOT EXISTS idx_quality_batches_status ON quality_batches(status);
CREATE INDEX IF NOT EXISTS idx_quality_results_batch ON quality_results(batch_id);
